# Generated by Django 5.2 on 2025-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchevent',
            name='startup',
        ),
        migrations.AlterField(
            model_name='pitchevent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StartupProfile',
        ),
    ]
