# Generated by Django 5.2 on 2025-04-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0002_remove_pitchevent_startup_alter_pitchevent_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchevent',
            name='investor_mail',
            field=models.EmailField(default='investor@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pitchevent',
            name='startup_mail',
            field=models.EmailField(default='startup@example.com', max_length=254),
        ),
    ]
